version: "3"
services:
  sonarqube:
    image: sonarqube
    ports:
      - 8081:9000
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - /home/ubuntu/environment/sonar/conf:/opt/sonarqube/conf
      - /home/ubuntu/environment/sonar/data:/opt/sonarqube/data
      - /home/ubuntu/environment/sonar/extensions:/opt/sonarqube/extensions
      - /home/ubuntu/environment/sonar/plugins:/opt/sonarqube/lib/bundled-plugins
  db:
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /home/ubuntu/environment/sonar/postgresql_data:/var/lib/postgresql/data
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
    container_name: jenkins
    volumes:
      - /home/ubuntu/environment/jenkins:/var/jenkins_home

